"""
Right-click runnable metrics launcher for outputs generated by run_batch_launcher.py.

This script computes IGD/rho and pairwise coverage **per run seed** (round-by-round),
instead of mixing all 15 runs together.

It reuses existing benchmark helpers under tools/benchmark/, but adapts the loader to
the flat output layout produced by run_batch_launcher.py:
  <output-dir>/<instance_stem>/
    fbea_run1.json
    fbea_unity_v2_run1.json
    ...
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Ensure project modules are importable without relying on external PYTHONPATH.
ROOT = Path(__file__).resolve().parents[1]
for extra in (ROOT, ROOT / "src", ROOT / "tools"):
    extra_str = extra.resolve().as_posix()
    if extra_str not in sys.path:
        sys.path.insert(0, extra_str)

from tools.benchmark.compute_metrics import compute_bounds, coverage, igd, rho  # type: ignore
from tools.benchmark.result_utils import (  # type: ignore
    aggregate_by_instance_and_seed,
    deduplicate,
    pareto_filter,
    tfn_c1,
)

EPS = 1e-12


def _parse_seed_from_filename(path: Path) -> Optional[int]:
    m = re.search(r"_run(\d+)\.json$", path.name)
    if not m:
        return None
    try:
        return int(m.group(1))
    except ValueError:
        return None


def _solution_from_dict(data: dict) -> dict:
    makespan = tuple(data["makespan"])
    energy = tuple(data["energy"])
    raw_dissatisfaction = data["dissatisfaction"] if "dissatisfaction" in data else data["agreement"]
    if isinstance(raw_dissatisfaction, (list, tuple)):
        dissatisfaction = data.get("dissatisfaction_c1", data.get("agreement_c1"))
        if dissatisfaction is None:
            dissatisfaction = tfn_c1(raw_dissatisfaction)
    else:
        dissatisfaction = raw_dissatisfaction
    makespan_c1 = data.get("makespan_c1")
    if makespan_c1 is None:
        makespan_c1 = tfn_c1(makespan)
    energy_c1 = data.get("energy_c1")
    if energy_c1 is None:
        energy_c1 = tfn_c1(energy)
    return {
        "makespan": makespan,
        "energy": energy,
        "agreement": float(dissatisfaction),
        "dissatisfaction": float(dissatisfaction),
        "makespan_c1": float(makespan_c1),
        "energy_c1": float(energy_c1),
    }


def _load_run_outputs_flat(runs_dir: Path) -> Dict[Tuple[str, str, str, int], List[dict]]:
    """
    Load run outputs from the flat directory layout produced by run_batch_launcher.py.
    Returns the same mapping shape used by tools/benchmark/compute_metrics.py:
      (algorithm, dataset_id, instance_id, seed) -> [solution_dict, ...]
    """
    results: Dict[Tuple[str, str, str, int], List[dict]] = {}
    for file in sorted(runs_dir.glob("*_run*.json")):
        try:
            data = json.loads(file.read_text(encoding="utf-8"))
        except Exception as exc:
            raise RuntimeError(f"Failed to read json: {file}") from exc

        algo_raw = data.get("algorithm") or file.name.split("_run", 1)[0]
        algorithm = str(algo_raw).strip().lower()

        dataset_id = str(data.get("dataset_id", "unknown")).strip()
        instance_id = str(data.get("instance_id", runs_dir.name)).strip()

        seed_raw = data.get("algorithm_seed", None)
        seed: Optional[int]
        if seed_raw is None:
            seed = _parse_seed_from_filename(file)
        else:
            try:
                seed = int(seed_raw)
            except Exception:
                seed = _parse_seed_from_filename(file)
        if seed is None:
            raise ValueError(f"Cannot determine run seed from {file.name}")

        raw_solutions = data.get("solutions", [])
        points = [_solution_from_dict(sol) for sol in raw_solutions]
        results[(algorithm, dataset_id, instance_id, seed)] = points
    return results


def _write_csv(path: Path, headers: List[str], rows: List[List[object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(rows)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Compute per-run (per seed) IGD/rho/coverage for batch outputs.")
    p.add_argument(
        "--runs-dir",
        default=None,
        help=(
            "Directory containing *_run*.json outputs (e.g. experiments/results/mk04/fbeavsv2/seed_7). "
            "If omitted, derived as <output-dir>/<stem(instance)>."
        ),
    )
    p.add_argument(
        "--instance",
        default=None,
        help="Prepared instance json used for the batch run (only used to derive runs-dir).",
    )
    p.add_argument(
        "--output-dir",
        default=None,
        help="Batch output root dir used by run_batch_launcher.py (only used to derive runs-dir).",
    )
    p.add_argument(
        "--summary",
        default=None,
        help="Summary CSV output path (default: <runs-dir>/metrics_summary_per_run.csv).",
    )
    p.add_argument(
        "--coverage",
        default=None,
        help="Coverage CSV output path (default: <runs-dir>/metrics_coverage_per_run.csv).",
    )
    return p.parse_args()


def default_args_for_quick_run() -> argparse.Namespace:
    """
    Quick-run defaults so you can right-click/run without typing CLI args.
    Adjust these values as needed.
    """
    ns = argparse.Namespace()
    ns.instance = str(
        ROOT
        / "experiments"
        / "prepared_instances"
        / "mk01"
        / "a=0.9-1.5"
        / "mk01"
        / "seed_101.json"
    )
    ns.output_dir = str(ROOT / "experiments" / "results" / "mk01" / "fbeavsV3" / "0.9-1.5")
    ns.runs_dir = None
    ns.summary = None
    ns.coverage = None
    return ns


def _resolve_runs_dir(args: argparse.Namespace) -> Path:
    if args.runs_dir:
        return Path(args.runs_dir).resolve()
    if not args.instance or not args.output_dir:
        raise ValueError("Either --runs-dir or both --instance and --output-dir must be provided.")
    instance_path = Path(args.instance).resolve()
    return (Path(args.output_dir).resolve() / instance_path.stem).resolve()


def main() -> None:
    args = parse_args() if len(sys.argv) > 1 else default_args_for_quick_run()
    runs_dir = _resolve_runs_dir(args)
    if not runs_dir.exists():
        raise FileNotFoundError(f"runs-dir not found: {runs_dir}")

    raw_outputs = _load_run_outputs_flat(runs_dir)
    if not raw_outputs:
        raise SystemExit(f"No *_run*.json found under {runs_dir}")

    # Build per-seed reference fronts (combine algorithms within the same seed).
    per_key_all_points: Dict[Tuple[str, str, int], List[dict]] = {}
    per_key_reference: Dict[Tuple[str, str, int], List[dict]] = {}
    for (algorithm, dataset_id, instance_id, seed), points in raw_outputs.items():
        key = (dataset_id, instance_id, seed)
        per_key_all_points.setdefault(key, []).extend(points)
        per_key_reference.setdefault(key, []).extend(points)
    reference_fronts = {k: pareto_filter(deduplicate(v)) for k, v in per_key_reference.items()}

    summary_rows: List[List[object]] = []
    for (algorithm, dataset_id, instance_id, seed), front in raw_outputs.items():
        front = pareto_filter(deduplicate(front))
        ref_key = (dataset_id, instance_id, seed)
        reference = reference_fronts.get(ref_key, [])
        bounds = compute_bounds(reference)
        # If any dimension in the reference bounds is degenerate, fall back to
        # per-seed aggregate bounds for that dimension to preserve distance information.
        if reference:
            agg_bounds = compute_bounds(per_key_all_points.get(ref_key, []))
            mixed_bounds: Dict[str, Tuple[float, float]] = {}
            for key in ("makespan_c1", "energy_c1", "agreement"):
                lo, hi = bounds[key]
                if hi - lo <= EPS:
                    lo2, hi2 = agg_bounds[key]
                    if hi2 - lo2 > EPS:
                        lo, hi = lo2, hi2
                mixed_bounds[key] = (lo, hi)
            bounds = mixed_bounds
        summary_rows.append(
            [
                algorithm,
                dataset_id,
                instance_id,
                seed,
                len(front),
                igd(front, reference, bounds),
                rho(front, reference),
            ]
        )

    summary_rows.sort(key=lambda r: (str(r[1]), str(r[2]), int(r[3]), str(r[0])))

    summary_path = Path(args.summary).resolve() if args.summary else runs_dir / "metrics_summary_per_run.csv"
    _write_csv(
        summary_path,
        ["algorithm", "dataset", "instance_id", "seed", "front_size", "igd", "rho"],
        summary_rows,
    )

    aggregated = {
        key: {algo: pareto_filter(points) for algo, points in algos.items()}
        for key, algos in aggregate_by_instance_and_seed(raw_outputs).items()
    }
    coverage_rows: List[List[object]] = []
    for (dataset_id, instance_id, seed), alg_fronts in aggregated.items():
        algo_names = sorted(alg_fronts.keys())
        for algo_a in algo_names:
            for algo_b in algo_names:
                if algo_a == algo_b:
                    continue
                coverage_rows.append(
                    [
                        dataset_id,
                        instance_id,
                        seed,
                        algo_a,
                        algo_b,
                        coverage(alg_fronts[algo_a], alg_fronts[algo_b]),
                    ]
                )

    coverage_rows.sort(key=lambda r: (str(r[0]), str(r[1]), int(r[2]), str(r[3]), str(r[4])))
    coverage_path = Path(args.coverage).resolve() if args.coverage else runs_dir / "metrics_coverage_per_run.csv"
    _write_csv(
        coverage_path,
        ["dataset", "instance_id", "seed", "algorithm_a", "algorithm_b", "coverage"],
        coverage_rows,
    )

    print(f"[ok] Wrote per-run metrics:\n  {summary_path}\n  {coverage_path}")


if __name__ == "__main__":
    main()
